build:
    maxIssues: 0

formatting:
    ArgumentListWrapping:
        maxLineLength: 145 # increased from 120
    ContextReceiverMapping:
        maxLineLength: 145 # increased from 120
    FunctionReturnTypeSpacing:
        maxLineLength: 145 # increased from 120
    FunctionSignature:
        maxLineLength: 145 # increased from 120
    MaximumLineLength:
        active: false
        maxLineLength: 145 # increased from 120
    ParameterListWrapping:
        maxLineLength: 145 # increased from 120
    ParameterWrapping:
        maxLineLength: 145 # increased from 120
    PropertyWrapping:
        maxLineLength: 145 # increased from 120
    Wrapping:
        maxLineLength: 145 # increased from 120

style:
    MaxLineLength:
        maxLineLength: 145 # increased from 120
    MagicNumber:
        excludes: [ "**/test/**","**/androidTest/**","**Test.kt","**Spec.kt","**Spek.kt","**.kts" ]

complexity:
    LongMethod:
        excludes: "**/test/**,**/androidTest/**,**/*.Test.kt,**/*.Spec.kt,**/*.Spek.kt"

exceptions:
    TooGenericExceptionThrown:
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**' ]

naming:
    FunctionNaming:
        ignoreAnnotated: [ 'Composable' ]
